// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  landlord: __t.option(__t.identity()),
  landlordSeat: __t.option(__t.u8()).name("landlord_seat"),
  currentTurn: __t.u8().name("current_turn"),
  multiple: __t.u8(),
  status: __t.string(),
  winner: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  lastActionTime: __t.timestamp().name("last_action_time"),
  turnStartTime: __t.option(__t.timestamp()).name("turn_start_time"),
  doublingMultiple: __t.u8().name("doubling_multiple"),
  currentDoublingTurn: __t.option(__t.u8()).name("current_doubling_turn"),
  isSpring: __t.bool().name("is_spring"),
  isAntiSpring: __t.bool().name("is_anti_spring"),
  landlordPlayCount: __t.u8().name("landlord_play_count"),
  bombCount: __t.u8().name("bomb_count"),
});
