// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import IdentityConnectedReducer from "./identity_connected_reducer";
import IdentityDisconnectedReducer from "./identity_disconnected_reducer";
import CheckBidTimeoutReducer from "./check_bid_timeout_reducer";
import CheckDoublingTimeoutReducer from "./check_doubling_timeout_reducer";
import CheckMatchQueueReducer from "./check_match_queue_reducer";
import CreateAiRoomReducer from "./create_ai_room_reducer";
import CreateRoomReducer from "./create_room_reducer";
import DoubleBetReducer from "./double_bet_reducer";
import EndGameReducer from "./end_game_reducer";
import JoinReducer from "./join_reducer";
import JoinMatchQueueReducer from "./join_match_queue_reducer";
import JoinRoomReducer from "./join_room_reducer";
import LeaveReducer from "./leave_reducer";
import LeaveMatchQueueReducer from "./leave_match_queue_reducer";
import LeaveRoomReducer from "./leave_room_reducer";
import PassTurnReducer from "./pass_turn_reducer";
import PauseGameReducer from "./pause_game_reducer";
import PlaceBidReducer from "./place_bid_reducer";
import PlayCardsReducer from "./play_cards_reducer";
import RestartGameReducer from "./restart_game_reducer";
import ResumeGameReducer from "./resume_game_reducer";
import ScheduleEmptyRoomCheckReducer from "./schedule_empty_room_check_reducer";
import SetReadyReducer from "./set_ready_reducer";
import SetTrustedReducer from "./set_trusted_reducer";
import StartAiActionScheduleReducer from "./start_ai_action_schedule_reducer";
import StartGameReducer from "./start_game_reducer";
import StartPeriodicCleanupReducer from "./start_periodic_cleanup_reducer";
import StartPeriodicMatchReducer from "./start_periodic_match_reducer";
import SubmitReportReducer from "./submit_report_reducer";
import TerminateAllGameRoomsReducer from "./terminate_all_game_rooms_reducer";
import TerminateMatchRoomsReducer from "./terminate_match_rooms_reducer";
import TriggerAiActionReducer from "./trigger_ai_action_reducer";
import UpdateAvatarReducer from "./update_avatar_reducer";
import UpdateNicknameReducer from "./update_nickname_reducer";
import UpdateSettingsReducer from "./update_settings_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import BidRow from "./bid_table";
import CurrentPlayRow from "./current_play_table";
import DoublingRow from "./doubling_table";
import GameRow from "./game_table";
import GameResultRow from "./game_result_table";
import LandlordCardsRow from "./landlord_cards_table";
import MatchQueueRow from "./match_queue_table";
import MatchRecordRow from "./match_record_table";
import PlayRow from "./play_table";
import PlayerHandRow from "./player_hand_table";
import ReportRow from "./report_table";
import RoomRow from "./room_table";
import RoomPauseRow from "./room_pause_table";
import RoomPlayerRow from "./room_player_table";
import ScoreHistoryRow from "./score_history_table";
import SystemNotificationRow from "./system_notification_table";
import UserRow from "./user_table";
import UserProfileRow from "./user_profile_table";
import UserSettingsRow from "./user_settings_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  bid: __table({
    name: 'bid',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'bid_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BidRow),
  current_play: __table({
    name: 'current_play',
    indexes: [
      { name: 'room_id', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'current_play_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, CurrentPlayRow),
  doubling: __table({
    name: 'doubling',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'doubling_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DoublingRow),
  game: __table({
    name: 'game',
    indexes: [
      { name: 'room_id', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'game_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, GameRow),
  game_result: __table({
    name: 'game_result',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'game_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameResultRow),
  landlord_cards: __table({
    name: 'landlord_cards',
    indexes: [
      { name: 'room_id', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'landlord_cards_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, LandlordCardsRow),
  match_queue: __table({
    name: 'match_queue',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'match_queue_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, MatchQueueRow),
  match_record: __table({
    name: 'match_record',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'match_record_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchRecordRow),
  play: __table({
    name: 'play',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'play_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayRow),
  player_hand: __table({
    name: 'player_hand',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'player_hand_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerHandRow),
  report: __table({
    name: 'report',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'report_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReportRow),
  room: __table({
    name: 'room',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'room_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoomRow),
  room_pause: __table({
    name: 'room_pause',
    indexes: [
      { name: 'room_id', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'room_pause_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, RoomPauseRow),
  room_player: __table({
    name: 'room_player',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'room_player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoomPlayerRow),
  score_history: __table({
    name: 'score_history',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'score_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ScoreHistoryRow),
  system_notification: __table({
    name: 'system_notification',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'target_identity', algorithm: 'btree', columns: [
        'targetIdentity',
      ] },
    ],
    constraints: [
      { name: 'system_notification_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SystemNotificationRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  user_profile: __table({
    name: 'user_profile',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserProfileRow),
  user_settings: __table({
    name: 'user_settings',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_settings_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserSettingsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("identity_connected", IdentityConnectedReducer),
  __reducerSchema("identity_disconnected", IdentityDisconnectedReducer),
  __reducerSchema("check_bid_timeout", CheckBidTimeoutReducer),
  __reducerSchema("check_doubling_timeout", CheckDoublingTimeoutReducer),
  __reducerSchema("check_match_queue", CheckMatchQueueReducer),
  __reducerSchema("create_ai_room", CreateAiRoomReducer),
  __reducerSchema("create_room", CreateRoomReducer),
  __reducerSchema("double_bet", DoubleBetReducer),
  __reducerSchema("end_game", EndGameReducer),
  __reducerSchema("join", JoinReducer),
  __reducerSchema("join_match_queue", JoinMatchQueueReducer),
  __reducerSchema("join_room", JoinRoomReducer),
  __reducerSchema("leave", LeaveReducer),
  __reducerSchema("leave_match_queue", LeaveMatchQueueReducer),
  __reducerSchema("leave_room", LeaveRoomReducer),
  __reducerSchema("pass_turn", PassTurnReducer),
  __reducerSchema("pause_game", PauseGameReducer),
  __reducerSchema("place_bid", PlaceBidReducer),
  __reducerSchema("play_cards", PlayCardsReducer),
  __reducerSchema("restart_game", RestartGameReducer),
  __reducerSchema("resume_game", ResumeGameReducer),
  __reducerSchema("schedule_empty_room_check", ScheduleEmptyRoomCheckReducer),
  __reducerSchema("set_ready", SetReadyReducer),
  __reducerSchema("set_trusted", SetTrustedReducer),
  __reducerSchema("start_ai_action_schedule", StartAiActionScheduleReducer),
  __reducerSchema("start_game", StartGameReducer),
  __reducerSchema("start_periodic_cleanup", StartPeriodicCleanupReducer),
  __reducerSchema("start_periodic_match", StartPeriodicMatchReducer),
  __reducerSchema("submit_report", SubmitReportReducer),
  __reducerSchema("terminate_all_game_rooms", TerminateAllGameRoomsReducer),
  __reducerSchema("terminate_match_rooms", TerminateMatchRoomsReducer),
  __reducerSchema("trigger_ai_action", TriggerAiActionReducer),
  __reducerSchema("update_avatar", UpdateAvatarReducer),
  __reducerSchema("update_nickname", UpdateNicknameReducer),
  __reducerSchema("update_settings", UpdateSettingsReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

