// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerIdentity: __t.identity().name("player_identity"),
  roomId: __t.u64().name("room_id"),
  isLandlord: __t.bool().name("is_landlord"),
  isWinner: __t.bool().name("is_winner"),
  scoreChange: __t.i32().name("score_change"),
  bombCount: __t.u8().name("bomb_count"),
  isSpring: __t.bool().name("is_spring"),
  createdAt: __t.timestamp().name("created_at"),
});
