// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  owner: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  currentPlayers: __t.u8().name("current_players"),
  isAiMode: __t.bool().name("is_ai_mode"),
  emptySince: __t.option(__t.timestamp()).name("empty_since"),
});
