// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AiActionSchedule = __t.object("AiActionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AiActionSchedule = __Infer<typeof AiActionSchedule>;

export const Bid = __t.object("Bid", {
  id: __t.u64(),
  roomId: __t.u64(),
  playerIdentity: __t.identity(),
  bidValue: __t.u8(),
  timestamp: __t.timestamp(),
});
export type Bid = __Infer<typeof Bid>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  roomId: __t.u64(),
  senderIdentity: __t.identity(),
  senderName: __t.string(),
  messageType: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const CurrentPlay = __t.object("CurrentPlay", {
  roomId: __t.u64(),
  playerIdentity: __t.identity(),
  cards: __t.byteArray(),
  combinationType: __t.string(),
});
export type CurrentPlay = __Infer<typeof CurrentPlay>;

export const Doubling = __t.object("Doubling", {
  id: __t.u64(),
  roomId: __t.u64(),
  playerIdentity: __t.identity(),
  doubled: __t.bool(),
  timestamp: __t.timestamp(),
});
export type Doubling = __Infer<typeof Doubling>;

export const EmptyRoomCheckSchedule = __t.object("EmptyRoomCheckSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.u64(),
});
export type EmptyRoomCheckSchedule = __Infer<typeof EmptyRoomCheckSchedule>;

export const Game = __t.object("Game", {
  roomId: __t.u64(),
  landlord: __t.option(__t.identity()),
  landlordSeat: __t.option(__t.u8()),
  currentTurn: __t.u8(),
  multiple: __t.u8(),
  status: __t.string(),
  winner: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  lastActionTime: __t.timestamp(),
  turnStartTime: __t.option(__t.timestamp()),
  doublingMultiple: __t.u8(),
  currentDoublingTurn: __t.option(__t.u8()),
  isSpring: __t.bool(),
  isAntiSpring: __t.bool(),
  landlordPlayCount: __t.u8(),
  bombCount: __t.u8(),
});
export type Game = __Infer<typeof Game>;

export const GameResult = __t.object("GameResult", {
  id: __t.u64(),
  roomId: __t.u64(),
  playerIdentity: __t.identity(),
  isLandlord: __t.bool(),
  isWinner: __t.bool(),
  baseScore: __t.i32(),
  bidMultiple: __t.u8(),
  doublingMultiple: __t.u8(),
  bombMultiple: __t.u8(),
  springMultiple: __t.u8(),
  finalScore: __t.i32(),
  createdAt: __t.timestamp(),
});
export type GameResult = __Infer<typeof GameResult>;

export const LandlordCards = __t.object("LandlordCards", {
  roomId: __t.u64(),
  cards: __t.byteArray(),
  revealed: __t.bool(),
});
export type LandlordCards = __Infer<typeof LandlordCards>;

export const MatchQueue = __t.object("MatchQueue", {
  identity: __t.identity(),
  score: __t.i64(),
  joinedAt: __t.timestamp(),
});
export type MatchQueue = __Infer<typeof MatchQueue>;

export const MatchRecord = __t.object("MatchRecord", {
  id: __t.u64(),
  playerIdentity: __t.identity(),
  roomId: __t.u64(),
  isLandlord: __t.bool(),
  isWinner: __t.bool(),
  scoreChange: __t.i32(),
  bombCount: __t.u8(),
  isSpring: __t.bool(),
  createdAt: __t.timestamp(),
});
export type MatchRecord = __Infer<typeof MatchRecord>;

export const PeriodicCleanupSchedule = __t.object("PeriodicCleanupSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PeriodicCleanupSchedule = __Infer<typeof PeriodicCleanupSchedule>;

export const PeriodicMatchSchedule = __t.object("PeriodicMatchSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PeriodicMatchSchedule = __Infer<typeof PeriodicMatchSchedule>;

export const Play = __t.object("Play", {
  id: __t.u64(),
  roomId: __t.u64(),
  playerIdentity: __t.identity(),
  cards: __t.byteArray(),
  combinationType: __t.string(),
  timestamp: __t.timestamp(),
});
export type Play = __Infer<typeof Play>;

export const PlayerHand = __t.object("PlayerHand", {
  id: __t.u64(),
  roomId: __t.u64(),
  playerIdentity: __t.identity(),
  cards: __t.byteArray(),
  isLandlord: __t.bool(),
  cardsCount: __t.u8(),
  playCount: __t.u8(),
});
export type PlayerHand = __Infer<typeof PlayerHand>;

export const RateLimit = __t.object("RateLimit", {
  id: __t.u64(),
  identity: __t.identity(),
  actionType: __t.string(),
  count: __t.u32(),
  windowStart: __t.timestamp(),
});
export type RateLimit = __Infer<typeof RateLimit>;

export const Report = __t.object("Report", {
  id: __t.u64(),
  reporter: __t.identity(),
  reported: __t.identity(),
  roomId: __t.u64(),
  reason: __t.string(),
  createdAt: __t.timestamp(),
});
export type Report = __Infer<typeof Report>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  name: __t.string(),
  owner: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  currentPlayers: __t.u8(),
  isAiMode: __t.bool(),
  emptySince: __t.option(__t.timestamp()),
});
export type Room = __Infer<typeof Room>;

export const RoomPause = __t.object("RoomPause", {
  roomId: __t.u64(),
  pausedBy: __t.identity(),
  pausedAt: __t.timestamp(),
});
export type RoomPause = __Infer<typeof RoomPause>;

export const RoomPlayer = __t.object("RoomPlayer", {
  id: __t.u64(),
  roomId: __t.u64(),
  playerIdentity: __t.identity(),
  playerName: __t.string(),
  seatIndex: __t.u8(),
  ready: __t.bool(),
  joinedAt: __t.timestamp(),
  isTrusted: __t.bool(),
  consecutiveTimeouts: __t.u8(),
  isAi: __t.bool(),
});
export type RoomPlayer = __Infer<typeof RoomPlayer>;

export const ScoreHistory = __t.object("ScoreHistory", {
  id: __t.u64(),
  playerIdentity: __t.identity(),
  change: __t.i32(),
  reason: __t.string(),
  matchId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type ScoreHistory = __Infer<typeof ScoreHistory>;

export const SystemNotification = __t.object("SystemNotification", {
  id: __t.u64(),
  targetIdentity: __t.identity(),
  notificationType: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp(),
});
export type SystemNotification = __Infer<typeof SystemNotification>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  createdAt: __t.timestamp(),
  totalGames: __t.u32(),
  wins: __t.u32(),
  score: __t.i64(),
});
export type User = __Infer<typeof User>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  avatarEmoji: __t.string(),
  nicknameUpdatedAt: __t.option(__t.timestamp()),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const UserSettings = __t.object("UserSettings", {
  identity: __t.identity(),
  soundEnabled: __t.bool(),
  musicEnabled: __t.bool(),
  animationEnabled: __t.bool(),
  cardSortOrder: __t.string(),
  tableTheme: __t.string(),
});
export type UserSettings = __Infer<typeof UserSettings>;

