// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import IdentityConnectedReducer from "../identity_connected_reducer";
import IdentityDisconnectedReducer from "../identity_disconnected_reducer";
import CheckBidTimeoutReducer from "../check_bid_timeout_reducer";
import CheckDoublingTimeoutReducer from "../check_doubling_timeout_reducer";
import CheckMatchQueueReducer from "../check_match_queue_reducer";
import CheckTurnTimeoutReducer from "../check_turn_timeout_reducer";
import CreateAiRoomReducer from "../create_ai_room_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DoubleBetReducer from "../double_bet_reducer";
import EndGameReducer from "../end_game_reducer";
import EnterSpectateModeReducer from "../enter_spectate_mode_reducer";
import ExitSpectateModeReducer from "../exit_spectate_mode_reducer";
import JoinReducer from "../join_reducer";
import JoinMatchQueueReducer from "../join_match_queue_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveReducer from "../leave_reducer";
import LeaveMatchQueueReducer from "../leave_match_queue_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import PassTurnReducer from "../pass_turn_reducer";
import PauseGameReducer from "../pause_game_reducer";
import PlaceBidReducer from "../place_bid_reducer";
import PlayCardsReducer from "../play_cards_reducer";
import RestartGameReducer from "../restart_game_reducer";
import ResumeGameReducer from "../resume_game_reducer";
import ScheduleEmptyRoomCheckReducer from "../schedule_empty_room_check_reducer";
import SetReadyReducer from "../set_ready_reducer";
import SetTrustedReducer from "../set_trusted_reducer";
import SpectateRoomReducer from "../spectate_room_reducer";
import StartAiActionScheduleReducer from "../start_ai_action_schedule_reducer";
import StartGameReducer from "../start_game_reducer";
import StartPeriodicCleanupReducer from "../start_periodic_cleanup_reducer";
import StartPeriodicMatchReducer from "../start_periodic_match_reducer";
import SubmitReportReducer from "../submit_report_reducer";
import TerminateAllGameRoomsReducer from "../terminate_all_game_rooms_reducer";
import TerminateMatchRoomsReducer from "../terminate_match_rooms_reducer";
import TriggerAiActionReducer from "../trigger_ai_action_reducer";
import UpdateAvatarReducer from "../update_avatar_reducer";
import UpdateNicknameReducer from "../update_nickname_reducer";
import UpdateSettingsReducer from "../update_settings_reducer";

export type IdentityConnectedParams = __Infer<typeof IdentityConnectedReducer>;
export type IdentityDisconnectedParams = __Infer<typeof IdentityDisconnectedReducer>;
export type CheckBidTimeoutParams = __Infer<typeof CheckBidTimeoutReducer>;
export type CheckDoublingTimeoutParams = __Infer<typeof CheckDoublingTimeoutReducer>;
export type CheckMatchQueueParams = __Infer<typeof CheckMatchQueueReducer>;
export type CheckTurnTimeoutParams = __Infer<typeof CheckTurnTimeoutReducer>;
export type CreateAiRoomParams = __Infer<typeof CreateAiRoomReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DoubleBetParams = __Infer<typeof DoubleBetReducer>;
export type EndGameParams = __Infer<typeof EndGameReducer>;
export type EnterSpectateModeParams = __Infer<typeof EnterSpectateModeReducer>;
export type ExitSpectateModeParams = __Infer<typeof ExitSpectateModeReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type JoinMatchQueueParams = __Infer<typeof JoinMatchQueueReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveParams = __Infer<typeof LeaveReducer>;
export type LeaveMatchQueueParams = __Infer<typeof LeaveMatchQueueReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type PassTurnParams = __Infer<typeof PassTurnReducer>;
export type PauseGameParams = __Infer<typeof PauseGameReducer>;
export type PlaceBidParams = __Infer<typeof PlaceBidReducer>;
export type PlayCardsParams = __Infer<typeof PlayCardsReducer>;
export type RestartGameParams = __Infer<typeof RestartGameReducer>;
export type ResumeGameParams = __Infer<typeof ResumeGameReducer>;
export type ScheduleEmptyRoomCheckParams = __Infer<typeof ScheduleEmptyRoomCheckReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type SetTrustedParams = __Infer<typeof SetTrustedReducer>;
export type SpectateRoomParams = __Infer<typeof SpectateRoomReducer>;
export type StartAiActionScheduleParams = __Infer<typeof StartAiActionScheduleReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type StartPeriodicCleanupParams = __Infer<typeof StartPeriodicCleanupReducer>;
export type StartPeriodicMatchParams = __Infer<typeof StartPeriodicMatchReducer>;
export type SubmitReportParams = __Infer<typeof SubmitReportReducer>;
export type TerminateAllGameRoomsParams = __Infer<typeof TerminateAllGameRoomsReducer>;
export type TerminateMatchRoomsParams = __Infer<typeof TerminateMatchRoomsReducer>;
export type TriggerAiActionParams = __Infer<typeof TriggerAiActionReducer>;
export type UpdateAvatarParams = __Infer<typeof UpdateAvatarReducer>;
export type UpdateNicknameParams = __Infer<typeof UpdateNicknameReducer>;
export type UpdateSettingsParams = __Infer<typeof UpdateSettingsReducer>;

